In [11]:
import geopandas as gpd
import pandas as pd
import numpy as np
from joblib import load

In [2]:
gdf = gpd.read_file("data/grid_ocean/gdf_microplastics_with_env.gpkg")
gdf

,mp_id,lat,lon,microplastics_measurement,unit,concentration_class_range,mesh_size_mm,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,profile_eco,dist_deg,geometry
0,0,45.280000,-60.290000,0.000000,pieces/m3,0-0.0005,0.3350,60.127269,6.299999,32.785152,0.509678,5.787156,0.834564,265.093384,57.033932,cold_shelf,0.350000,POINT (-60.29 45.28)
1,1,40.930000,-70.650000,0.002276,pieces/m3,0.0005-0.005,0.3350,39.954054,12.127690,34.283134,0.336776,5.251710,0.567093,248.744659,25.638559,cold_shelf,0.165529,POINT (-70.65 40.93)
2,2,40.930000,-70.650000,0.004320,pieces/m3,0.0005-0.005,0.3350,39.954054,12.127690,34.283134,0.336776,5.251710,0.567093,248.744659,25.638559,cold_shelf,0.165529,POINT (-70.65 40.93)
3,3,40.300000,-69.770000,0.000000,pieces/m3,0-0.0005,0.3350,82.057580,12.127690,34.283134,0.494065,5.251710,0.567093,248.744659,25.638559,cold_shelf,0.304795,POINT (-69.77 40.3)
4,4,39.880000,-67.150000,0.000000,pieces/m3,0-0.0005,0.3350,357.363239,8.405213,35.200493,0.848809,14.126949,0.930865,236.792160,56.462185,open_sea_temperate,0.192094,POINT (-67.15 39.88)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14150,19317,-5.933333,39.360000,188.300000,pieces kg-1 d.w.,150-200,0.0007,102.177974,13.464818,34.985344,0.003898,21.074507,1.583272,147.353027,115.873299,open_sea_temperate,1.141948,POINT (39.36 -5.93333)
14151,19318,-5.500000,39.120000,155.270000,pieces kg-1 d.w.,150-200,0.0007,46.901614,17.833050,35.093750,0.142112,14.431973,1.130769,162.590759,78.066124,open_sea_temperate,1.332066,POINT (39.12 -5.5)
14152,19319,-6.450000,39.466667,58.070000,pieces kg-1 d.w.,20-150,0.0007,49.536977,16.662235,35.049408,-0.258756,16.213150,1.203066,166.246719,81.130661,open_sea_temperate,0.766123,POINT (39.46667 -6.45)
14153,19320,-6.320000,39.210000,210.000000,pieces kg-1 d.w.,>200,0.0007,49.536977,16.662235,35.049408,-0.258756,16.213150,1.203066,166.246719,81.130661,open_sea_temperate,1.042353,POINT (39.21 -6.32)
14154,19321,-6.110000,39.150000,208.330000,pieces kg-1 d.w.,>200,0.0007,49.536977,16.662235,35.049408,-0.258756,16.213150,1.203066,166.246719,81.130661,open_sea_temperate,1.230691,POINT (39.15 -6.11)

In [3]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 14155 entries, 0 to 14154
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   mp_id                      14155 non-null  int64
 1   lat                        14155 non-null  float64
 2   lon                        14155 non-null  float64
 3   microplastics_measurement  14155 non-null  float64
 4   unit                       14155 non-null  object
 5   concentration_class_range  14155 non-null  object
 6   mesh_size_mm               14155 non-null  float64
 7   distance_to_coast_km       14155 non-null  float64
 8   temperature                14155 non-null  float32
 9   salinity                   14155 non-null  float32
 10  chlorophyll                14155 non-null  float32
 11  nitrate                    14155 non-null  float32
 12  phosphate                  14155 non-null  float32
 13  oxygen_dissolved           14155 non-null  float32
 14  oxygen_utilization         14155 non-null  float32
 15  profile_eco                14155 non-null  object
 16  dist_deg                   14155 non-null  float64
 17  geometry                   14155 non-null  geometry
dtypes: float32(7), float64(6), geometry(1), int64(1), object(3)
memory usage: 1.6+ MB

In [4]:
gdf.describe()

,mp_id,lat,lon,microplastics_measurement,mesh_size_mm,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,dist_deg
count,14155.000000,14155.000000,14155.000000,14155.000000,14155.000000,14155.000000,14155.000000,14155.000000,14155.000000,14155.000000,14155.000000,14155.000000,14155.000000,14155.000000
mean,7416.833133,24.952454,-44.699393,504.973226,0.285739,334.483972,12.832611,35.128117,0.047165,13.292573,0.971803,200.357010,70.024673,0.567941
std,4777.276240,22.160621,75.558764,9254.932732,0.141124,485.634551,5.845214,2.135643,1.667265,8.687100,0.624379,49.678261,54.866306,2.034330
min,0.000000,-71.699040,-179.994200,0.000000,0.000450,0.727276,-1.495278,5.000000,-4.241218,0.002430,0.023326,37.909927,-5.241513,0.000000
25%,3538.500000,16.970000,-79.575000,0.002000,0.330000,39.954054,9.411748,34.569160,-0.484223,5.787088,0.536706,172.780487,32.765865,0.162788
50%,7077.000000,26.849250,-64.960000,0.017280,0.335000,95.652948,11.128823,35.353649,-0.088101,12.858278,0.855791,202.394287,54.665913,0.234307
75%,10615.500000,38.703333,-6.251834,0.312500,0.335000,421.510350,14.800588,35.675385,0.431647,17.585995,1.269217,230.547836,90.241318,0.373358
max,19321.000000,89.761400,179.854333,800000.000000,1.130000,2536.054891,29.194981,40.411633,98.591469,36.618423,2.740523,375.720337,249.339386,35.402928

In [5]:
import numpy as np
mp_observed = gdf["microplastics_measurement"].dropna().values
MP_REF_P90 = np.percentile(mp_observed, 90)
MP_REF_P90

np.float64(5.28005960000001)

In [3]:
gdf2 = gpd.read_file('data/grid_indice/hazard_index_grid_final.gpkg')
gdf2.head()

,sci_name,redlistCategory,iucn_id,vuln,mp_pieces_m3,dist_m,x,y,cell_id,index_right,...,eco_shape_richness,ecotaxa_present,FIBER,FRAGMENT,SPHERE,OTHER,hazard_pressure,hazard_morphology,hazard_index,geometry
0,Hubbsina turneri,CR,0,4,2115.655853,244627.454273,-9.791379e+06,2.486198e+06,9910,24025,...,3,1,0.62069,0.068966,0.0,0.310345,0.006732,0.731034,0.368883,POINT (-9791379.477 2486197.52)
1,Ictalurus mexicanus,VU,3,2,2820.874471,176956.192726,-9.586314e+06,2.737598e+06,10174,24025,...,3,1,0.62069,0.068966,0.0,0.310345,0.008014,0.731034,0.369524,POINT (-9586314.291 2737597.95)
2,Ameca splendens,CR,5,4,6346.967560,145126.276485,-1.004222e+07,2.609194e+06,9649,24025,...,3,1,0.62069,0.068966,0.0,0.310345,0.017544,0.731034,0.374289,POINT (-10042224.508 2609193.916)
3,Ameca splendens,CR,13,4,4231.311707,138592.329475,-9.987758e+06,2.495868e+06,9648,24025,...,3,1,0.62069,0.068966,0.0,0.310345,0.012021,0.731034,0.371528,POINT (-9987758.003 2495868.065)
4,Lucania interioris,EN,15,3,21156.558533,661939.173782,-9.851249e+06,3.313858e+06,9918,24025,...,3,1,0.62069,0.068966,0.0,0.310345,0.059315,0.731034,0.395175,POINT (-9851249.069 3313858.185)

In [13]:
# prueba manual
tests = pd.DataFrame([
    {"eco_shape_richness": 2, "ecotaxa_present": 1, "vuln": 1},
    {"eco_shape_richness": 2, "ecotaxa_present": 1, "vuln": 3},
    {"eco_shape_richness": 4, "ecotaxa_present": 1, "vuln": 1},
    {"eco_shape_richness": 4, "ecotaxa_present": 1, "vuln": 4},
    {"eco_shape_richness": 2, "ecotaxa_present": 0, "vuln": 0},
])

# cargar modelo
model = load("models/Grilla_hazard/model_hazard.joblib")

# predicción
probas = model.predict_proba(tests)

probas

array([[0.82711068, 0.17288932],
       [0.32945063, 0.67054937],
       [1.        , 0.        ],
       [0.93907734, 0.06092266],
       [0.82711068, 0.17288932]])

In [15]:
gdf3 = gpd.read_file('data/Predicciones/species_count_prediction_with_confidence.gpkg')
gdf3.head()

,cell_id,sci_name,redlistCategory,iucn_id,vuln,mp_pieces_m3,dist_m,x,y,object_area,...,oxygen_utilization,variables_dist_m,vars_distance_km,vars_confidence,log_dist_m,pred_iucn_mean_risk,confidence_label,pred_log_iucn_species_count,pred_iucn_species_count,geometry
0,29119,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,104.338974,0.0,0.0,exact,NaN,2.044704,alta,0.705637,1.025137,"POLYGON ((4936734.248 -2333533.078, 4936734.24..."
1,29127,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,108.766624,0.0,0.0,exact,NaN,2.098523,alta,0.704868,1.023579,"POLYGON ((4936734.248 -1533533.078, 4936734.24..."
2,29126,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,108.766624,0.0,0.0,exact,NaN,2.082851,alta,0.705337,1.024529,"POLYGON ((4936734.248 -1633533.078, 4936734.24..."
3,29125,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,124.115204,0.0,0.0,exact,NaN,2.077402,alta,0.706086,1.026045,"POLYGON ((4936734.248 -1733533.078, 4936734.24..."
4,29124,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,120.052605,0.0,0.0,exact,NaN,2.085751,alta,0.705485,1.024828,"POLYGON ((4936734.248 -1833533.078, 4936734.24..."