In [1]:
import geopandas as gpd

In [14]:
gdf = gpd.read_file("data/grid_indice/hazard_index_grid_final.gpkg")
gdf

,sci_name,redlistCategory,iucn_id,vuln,mp_pieces_m3,dist_m,x,y,cell_id,index_right,...,eco_shape_richness,ecotaxa_present,FIBER,FRAGMENT,SPHERE,OTHER,hazard_pressure,hazard_morphology,hazard_index,geometry
0,Hubbsina turneri,CR,0,4,2115.655853,244627.454273,-9.791379e+06,2.486198e+06,9910,24025,...,3,1,0.620690,0.068966,0.0,0.310345,6.731632e-03,0.731034,0.368883,POINT (-9791379.477 2486197.52)
1,Ictalurus mexicanus,VU,3,2,2820.874471,176956.192726,-9.586314e+06,2.737598e+06,10174,24025,...,3,1,0.620690,0.068966,0.0,0.310345,8.013848e-03,0.731034,0.369524,POINT (-9586314.291 2737597.95)
2,Ameca splendens,CR,5,4,6346.967560,145126.276485,-1.004222e+07,2.609194e+06,9649,24025,...,3,1,0.620690,0.068966,0.0,0.310345,1.754383e-02,0.731034,0.374289,POINT (-10042224.508 2609193.916)
3,Ameca splendens,CR,13,4,4231.311707,138592.329475,-9.987758e+06,2.495868e+06,9648,24025,...,3,1,0.620690,0.068966,0.0,0.310345,1.202077e-02,0.731034,0.371528,POINT (-9987758.003 2495868.065)
4,Lucania interioris,EN,15,3,21156.558533,661939.173782,-9.851249e+06,3.313858e+06,9918,24025,...,3,1,0.620690,0.068966,0.0,0.310345,5.931462e-02,0.731034,0.395175,POINT (-9851249.069 3313858.185)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3159,Parvulastra vivipara,CR,70168,4,0.003000,15969.178933,1.423184e+07,-4.985387e+06,41275,1983,...,2,1,0.835052,0.000000,0.0,0.164948,8.484848e-09,0.868041,0.434021,POINT (14231843.085 -4985387.297)
3160,Parvulastra vivipara,CR,70215,4,0.003000,26833.830819,1.423741e+07,-4.977844e+06,41406,1983,...,2,1,0.835052,0.000000,0.0,0.164948,4.854460e-08,0.868041,0.434021,POINT (14237410.247 -4977844.387)
3161,Macrobrachium thysi,VU,70263,2,0.038661,873655.188787,-3.915153e+05,6.895345e+05,22206,108,...,3,1,0.693878,0.163265,0.0,0.142857,1.098324e-07,0.836735,0.418367,POINT (-391515.274 689534.48)
3162,Macrobrachium thysi,VU,70265,2,0.038661,955117.135523,-2.972588e+05,6.644734e+05,22336,108,...,3,1,0.693878,0.163265,0.0,0.142857,1.098324e-07,0.836735,0.418367,POINT (-297258.792 664473.402)
3163,Macrobrachium thysi,VU,70269,2,0.038661,929073.410690,-3.397301e+05,7.005476e+05,22337,108,...,3,1,0.693878,0.163265,0.0,0.142857,1.098324e-07,0.836735,0.418367,POINT (-339730.122 700547.573)

In [3]:
gdf_profile = gpd.read_file("data/grid_ocean/grilla_agua_perfiles.gpkg")
gdf_profile

,lat,lon,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,cluster_num,profile_eco,geometry
0,-78.0,-175.5,543.707048,-1.775068,34.395912,1.680748,27.419722,1.907441,311.153168,59.152695,5,cold_open_sea,POINT (-175.5 -78)
1,-78.0,-175.0,533.294654,-1.775068,34.395912,1.243596,27.419722,1.907441,311.153168,59.152695,5,cold_open_sea,POINT (-175 -78)
2,-78.0,-173.0,543.143622,-1.808737,34.373737,-0.760849,27.574869,1.912899,312.213226,57.888039,5,cold_open_sea,POINT (-173 -78)
3,-78.0,-172.5,540.559218,-1.808737,34.373737,-0.805667,27.574869,1.912899,312.213226,57.888039,5,cold_open_sea,POINT (-172.5 -78)
4,-78.0,-172.0,535.905487,-1.808737,34.373737,-0.708566,27.574869,1.912899,312.213226,57.888039,5,cold_open_sea,POINT (-172 -78)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
127006,72.0,-15.0,425.634963,0.289420,34.764435,0.504466,11.316046,0.823883,318.571198,32.765865,1,cold_shelf,POINT (-15 72)
127007,72.0,25.5,94.266326,6.833642,34.894951,0.065487,6.138589,0.608244,298.023193,4.414944,1,cold_shelf,POINT (25.5 72)
127008,72.0,26.5,110.341777,6.723017,34.888157,0.365244,5.862425,0.607004,298.572815,4.962784,1,cold_shelf,POINT (26.5 72)
127009,72.0,27.0,111.642511,6.723017,34.888157,-0.597254,5.862425,0.607004,298.572815,4.962784,1,cold_shelf,POINT (27 72)
127010,72.0,27.5,98.314809,6.519808,34.888569,-0.687283,5.836751,0.615934,299.227234,5.952769,1,cold_shelf,POINT (27.5 72)

In [4]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 19322 entries, 0 to 19321
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   microplastics_measurement  14197 non-null  float64
 1   unit                       19322 non-null  object
 2   concentration_class_range  19322 non-null  object
 3   mesh_size_mm               14155 non-null  float64
 4   lat                        19322 non-null  float64
 5   lon                        19322 non-null  float64
 6   geometry                   19322 non-null  geometry
dtypes: float64(4), geometry(1), object(2)
memory usage: 1.0+ MB

In [5]:
gdf_profile.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 127011 entries, 0 to 127010
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   lat                   127011 non-null  float64
 1   lon                   127011 non-null  float64
 2   distance_to_coast_km  127011 non-null  float64
 3   temperature           127011 non-null  float32
 4   salinity              127011 non-null  float32
 5   chlorophyll           127011 non-null  float32
 6   nitrate               127011 non-null  float32
 7   phosphate             127011 non-null  float32
 8   oxygen_dissolved      127011 non-null  float32
 9   oxygen_utilization    127011 non-null  float32
 10  cluster_num           127011 non-null  int32
 11  profile_eco           127011 non-null  object
 12  geometry              127011 non-null  geometry
dtypes: float32(7), float64(3), geometry(1), int32(1), object(1)
memory usage: 8.7+ MB

In [6]:
gdf = gdf.to_crs(gdf_profile.crs)

gdf = gpd.sjoin(
    gdf,
    gdf_profile[["geometry", "profile_eco"]],
    how="left",
    predicate="intersects",
)

gdf = gdf.drop(columns=["index_right"])
gdf

,microplastics_measurement,unit,concentration_class_range,mesh_size_mm,lat,lon,geometry,profile_eco
0,0.000000,pieces/m3,0-0.0005,0.3350,45.280000,-60.290000,POINT (-60.29 45.28),NaN
1,0.002276,pieces/m3,0.0005-0.005,0.3350,40.930000,-70.650000,POINT (-70.65 40.93),NaN
2,0.004320,pieces/m3,0.0005-0.005,0.3350,40.930000,-70.650000,POINT (-70.65 40.93),NaN
3,0.000000,pieces/m3,0-0.0005,0.3350,40.300000,-69.770000,POINT (-69.77 40.3),NaN
4,0.000000,pieces/m3,0-0.0005,0.3350,39.880000,-67.150000,POINT (-67.15 39.88),NaN
...,...,...,...,...,...,...,...,...
19317,188.300000,pieces kg-1 d.w.,150-200,0.0007,-5.933333,39.360000,POINT (39.36 -5.93333),NaN
19318,155.270000,pieces kg-1 d.w.,150-200,0.0007,-5.500000,39.120000,POINT (39.12 -5.5),NaN
19319,58.070000,pieces kg-1 d.w.,20-150,0.0007,-6.450000,39.466667,POINT (39.46667 -6.45),NaN
19320,210.000000,pieces kg-1 d.w.,>200,0.0007,-6.320000,39.210000,POINT (39.21 -6.32),NaN
19321,208.330000,pieces kg-1 d.w.,>200,0.0007,-6.110000,39.150000,POINT (39.15 -6.11),NaN

In [16]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 3164 entries, 0 to 3163
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sci_name            3164 non-null   object
 1   redlistCategory     3164 non-null   object
 2   iucn_id             3164 non-null   int64
 3   vuln                3164 non-null   int64
 4   mp_pieces_m3        3164 non-null   float64
 5   dist_m              3164 non-null   float64
 6   x                   3164 non-null   float64
 7   y                   3164 non-null   float64
 8   cell_id             3164 non-null   int64
 9   index_right         3164 non-null   int64
 10  object_area         3164 non-null   float64
 11  shape               3164 non-null   object
 12  eco_dist_m          3164 non-null   float64
 13  noaa_mp_mean        3164 non-null   float64
 14  noaa_mp_max         3164 non-null   float64
 15  noaa_mp_count       3164 non-null   int64
 16  iucn_species_count  3164 non-null   int64
 17  iucn_mean_risk      3164 non-null   float64
 18  iucn_max_risk       3164 non-null   int64
 19  eco_count           3164 non-null   int64
 20  eco_mean_size       3164 non-null   float64
 21  eco_small_ratio     3164 non-null   float64
 22  eco_shape_richness  3164 non-null   int64
 23  ecotaxa_present     3164 non-null   int64
 24  FIBER               3164 non-null   float64
 25  FRAGMENT            3164 non-null   float64
 26  SPHERE              3164 non-null   float64
 27  OTHER               3164 non-null   float64
 28  hazard_pressure     3164 non-null   float64
 29  hazard_morphology   3164 non-null   float64
 30  hazard_index        3164 non-null   float64
 31  geometry            3164 non-null   geometry
dtypes: float64(18), geometry(1), int64(10), object(3)
memory usage: 791.1+ KB

In [15]:
gdf.describe()

,iucn_id,vuln,mp_pieces_m3,dist_m,x,y,cell_id,index_right,object_area,eco_dist_m,...,eco_small_ratio,eco_shape_richness,ecotaxa_present,FIBER,FRAGMENT,SPHERE,OTHER,hazard_pressure,hazard_morphology,hazard_index
count,3164.000000,3164.000000,3164.000000,3.164000e+03,3.164000e+03,3.164000e+03,3164.000000,3164.000000,3164.000000,3.164000e+03,...,3164.000000,3164.000000,3164.0,3164.000000,3164.000000,3164.000000,3164.000000,3.164000e+03,3164.000000,3164.000000
mean,23597.930784,1.844185,1871.876047,5.167827e+05,-8.059690e+04,1.873123e+06,22658.392225,8409.071113,4593.987990,5.745439e+06,...,0.889269,3.019279,1.0,0.660326,0.115925,0.000652,0.223097,5.248326e-03,0.786353,0.395801
std,23082.697787,0.845696,19228.666673,5.897001e+05,7.886687e+06,3.387511e+06,10326.149149,9751.921805,5824.528202,3.517022e+06,...,0.077159,0.346531,0.0,0.124984,0.115051,0.003161,0.075724,5.410335e-02,0.063504,0.042221
min,0.000000,1.000000,0.000000,4.008449e+02,-1.736327e+07,-6.032789e+06,9.000000,4.000000,647.000000,1.611718e+04,...,0.492239,2.000000,1.0,0.055556,0.000000,0.000000,0.076923,0.000000e+00,0.418182,0.209091
25%,5225.000000,1.000000,0.002675,1.179090e+05,-6.559799e+06,-7.580087e+05,14162.750000,2078.250000,1340.000000,2.782265e+06,...,0.877551,3.000000,1.0,0.620690,0.068966,0.000000,0.173410,8.522727e-09,0.731034,0.365517
50%,12464.000000,2.000000,0.028497,3.090258e+05,-3.906014e+05,2.353172e+06,22254.500000,3594.000000,1340.000000,5.220600e+06,...,0.896552,3.000000,1.0,0.693878,0.075472,0.000000,0.188679,1.043580e-07,0.826415,0.413208
75%,33664.250000,2.000000,0.777778,6.942777e+05,4.434378e+06,4.936178e+06,28545.250000,24025.000000,10328.000000,9.178400e+06,...,0.924528,3.000000,1.0,0.735849,0.163265,0.000000,0.310345,3.395950e-06,0.826415,0.413428
max,70269.000000,4.000000,352000.000000,4.577436e+06,1.729999e+07,6.977287e+06,45375.000000,24026.000000,131391.000000,1.191143e+07,...,1.000000,4.000000,1.0,0.877551,0.669623,0.038217,0.727273,1.000000e+00,0.923077,0.913208

In [17]:
import numpy as np

mp_observed = gdf["noaa_mp_mean"].dropna().values
MP_REF_P90 = np.percentile(mp_observed, 90)
MP_REF_P90

np.float64(2052.0)