In [11]:
import geopandas as gpd
import pandas as pd
import numpy as np
from joblib import load

In [2]:
gdf = gpd.read_file("data/Predicciones/mapa_continuo.gpkg")
gdf

,lat,lon,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,microplastics_log_est,microplastics_est,profile_eco,geometry
0,-78.0,-175.5,543.707048,-1.775068,34.395912,1.680748,27.419722,1.907441,311.153168,59.152695,0.211114,0.235053,cold_open_sea,POINT (-175.5 -78)
1,-78.0,-175.0,533.294654,-1.775068,34.395912,1.243596,27.419722,1.907441,311.153168,59.152695,0.210195,0.233919,cold_open_sea,POINT (-175 -78)
2,-78.0,-173.0,543.143622,-1.808737,34.373737,-0.760849,27.574869,1.912899,312.213226,57.888039,0.308657,0.361595,cold_open_sea,POINT (-173 -78)
3,-78.0,-172.5,540.559218,-1.808737,34.373737,-0.805667,27.574869,1.912899,312.213226,57.888039,0.308657,0.361595,cold_open_sea,POINT (-172.5 -78)
4,-78.0,-172.0,535.905487,-1.808737,34.373737,-0.708566,27.574869,1.912899,312.213226,57.888039,0.308657,0.361595,cold_open_sea,POINT (-172 -78)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127008,72.0,-15.0,425.634963,0.289420,34.764435,0.504466,11.316046,0.823883,318.571198,32.765865,0.315589,0.371066,cold_shelf,POINT (-15 72)
127009,72.0,25.5,94.266326,6.833642,34.894951,0.065487,6.138589,0.608244,298.023193,4.414944,0.395133,0.484582,cold_shelf,POINT (25.5 72)
127010,72.0,26.5,110.341777,6.723017,34.888157,0.365244,5.862425,0.607004,298.572815,4.962784,0.355206,0.426474,cold_shelf,POINT (26.5 72)
127011,72.0,27.0,111.642511,6.723017,34.888157,-0.597254,5.862425,0.607004,298.572815,4.962784,0.331746,0.393399,cold_shelf,POINT (27 72)
127012,72.0,27.5,98.314809,6.519808,34.888569,-0.687283,5.836751,0.615934,299.227234,5.952769,0.316624,0.372486,cold_shelf,POINT (27.5 72)

In [3]:
print(gdf.geometry.x.min(), gdf.geometry.x.max())
print(gdf.geometry.y.min(), gdf.geometry.y.max())

-179.5 179.5
-78.0 72.0

In [4]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 127013 entries, 0 to 127012
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   lat                    127013 non-null  float64
 1   lon                    127013 non-null  float64
 2   distance_to_coast_km   127013 non-null  float64
 3   temperature            127013 non-null  float32
 4   salinity               127013 non-null  float32
 5   chlorophyll            127013 non-null  float32
 6   nitrate                127013 non-null  float32
 7   phosphate              127013 non-null  float32
 8   oxygen_dissolved       127013 non-null  float32
 9   oxygen_utilization     127013 non-null  float32
 10  microplastics_log_est  127013 non-null  float64
 11  microplastics_est      127013 non-null  float64
 12  profile_eco            127011 non-null  object
 13  geometry               127013 non-null  geometry
dtypes: float32(7), float64(5), geometry(1), object(1)
memory usage: 10.2+ MB

In [5]:
print(gdf.crs)

EPSG:4326

In [6]:
gdf.describe()

,lat,lon,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,microplastics_log_est,microplastics_est
count,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000
mean,-10.007543,-9.046928,750.044877,7.997197,34.678719,0.532300,23.052828,1.671279,188.177490,110.283775,0.383477,28.486041
std,35.009586,111.011041,571.628432,4.463955,1.264769,6.216773,7.026030,0.502678,52.864658,48.267570,0.599799,673.731594
min,-78.000000,-179.500000,0.103413,-1.850811,5.000000,-1366.265503,0.000000,0.023326,37.909927,-5.241513,0.004230,0.004239
25%,-40.500000,-111.000000,278.209049,5.151471,34.468796,-0.269659,19.575056,1.410686,141.790955,81.606102,0.166744,0.181451
50%,-13.000000,-21.500000,620.359049,8.658937,34.672611,0.265012,24.424078,1.763284,197.913284,100.916283,0.267175,0.306270
75%,17.500000,90.500000,1110.119925,10.146996,34.979290,0.994706,28.254725,2.041040,230.406204,149.964447,0.436245,0.546888
max,72.000000,179.500000,2747.629560,30.365410,40.431507,853.870911,36.994316,5.037070,381.294861,250.507050,10.127362,25017.268590

In [13]:
gdf.iloc[[74490]]

,lat,lon,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,microplastics_log_est,microplastics_est,profile_eco,geometry
74490,-2.5,-16.5,641.785567,9.149076,35.111168,-0.177002,20.304949,1.38483,191.36409,96.799782,0.197725,0.218627,open_sea_temperate,POINT (-16.5 -2.5)

In [8]:
import numpy as np
y_pred = 0.106
y_real = float(np.expm1(y_pred))
y_real

0.11182187650653083

In [9]:
gdf2 = gpd.read_file("data/grid_ocean/grilla_agua_perfiles.gpkg")

In [14]:
gdf2.iloc[[74490]]

,lat,lon,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,cluster_num,profile_eco,geometry
74490,-2.5,-15.5,609.825644,9.275754,35.114262,-0.404584,20.07222,1.371136,189.492386,97.762413,0,open_sea_temperate,POINT (-15.5 -2.5)

In [11]:
y_pred2 = 0.106
y_real2 = float(np.expm1(y_pred))
y_real2

0.11182187650653083

In [12]:
print(gdf2.crs)

EPSG:4326

In [3]:
gdf2 = gpd.read_file('data/grid_indice/hazard_index_grid_final.gpkg')
gdf2.head()

,sci_name,redlistCategory,iucn_id,vuln,mp_pieces_m3,dist_m,x,y,cell_id,index_right,...,eco_shape_richness,ecotaxa_present,FIBER,FRAGMENT,SPHERE,OTHER,hazard_pressure,hazard_morphology,hazard_index,geometry
0,Hubbsina turneri,CR,0,4,2115.655853,244627.454273,-9.791379e+06,2.486198e+06,9910,24025,...,3,1,0.62069,0.068966,0.0,0.310345,0.006732,0.731034,0.368883,POINT (-9791379.477 2486197.52)
1,Ictalurus mexicanus,VU,3,2,2820.874471,176956.192726,-9.586314e+06,2.737598e+06,10174,24025,...,3,1,0.62069,0.068966,0.0,0.310345,0.008014,0.731034,0.369524,POINT (-9586314.291 2737597.95)
2,Ameca splendens,CR,5,4,6346.967560,145126.276485,-1.004222e+07,2.609194e+06,9649,24025,...,3,1,0.62069,0.068966,0.0,0.310345,0.017544,0.731034,0.374289,POINT (-10042224.508 2609193.916)
3,Ameca splendens,CR,13,4,4231.311707,138592.329475,-9.987758e+06,2.495868e+06,9648,24025,...,3,1,0.62069,0.068966,0.0,0.310345,0.012021,0.731034,0.371528,POINT (-9987758.003 2495868.065)
4,Lucania interioris,EN,15,3,21156.558533,661939.173782,-9.851249e+06,3.313858e+06,9918,24025,...,3,1,0.62069,0.068966,0.0,0.310345,0.059315,0.731034,0.395175,POINT (-9851249.069 3313858.185)

In [13]:
# prueba manual
tests = pd.DataFrame([
    {"eco_shape_richness": 2, "ecotaxa_present": 1, "vuln": 1},
    {"eco_shape_richness": 2, "ecotaxa_present": 1, "vuln": 3},
    {"eco_shape_richness": 4, "ecotaxa_present": 1, "vuln": 1},
    {"eco_shape_richness": 4, "ecotaxa_present": 1, "vuln": 4},
    {"eco_shape_richness": 2, "ecotaxa_present": 0, "vuln": 0},
])

# cargar modelo
model = load("models/Grilla_hazard/model_hazard.joblib")

# predicción
probas = model.predict_proba(tests)

probas

array([[0.82711068, 0.17288932],
       [0.32945063, 0.67054937],
       [1.        , 0.        ],
       [0.93907734, 0.06092266],
       [0.82711068, 0.17288932]])

In [15]:
gdf3 = gpd.read_file('data/Predicciones/species_count_prediction_with_confidence.gpkg')
gdf3.head()

,cell_id,sci_name,redlistCategory,iucn_id,vuln,mp_pieces_m3,dist_m,x,y,object_area,...,oxygen_utilization,variables_dist_m,vars_distance_km,vars_confidence,log_dist_m,pred_iucn_mean_risk,confidence_label,pred_log_iucn_species_count,pred_iucn_species_count,geometry
0,29119,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,104.338974,0.0,0.0,exact,NaN,2.044704,alta,0.705637,1.025137,"POLYGON ((4936734.248 -2333533.078, 4936734.24..."
1,29127,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,108.766624,0.0,0.0,exact,NaN,2.098523,alta,0.704868,1.023579,"POLYGON ((4936734.248 -1533533.078, 4936734.24..."
2,29126,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,108.766624,0.0,0.0,exact,NaN,2.082851,alta,0.705337,1.024529,"POLYGON ((4936734.248 -1633533.078, 4936734.24..."
3,29125,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,124.115204,0.0,0.0,exact,NaN,2.077402,alta,0.706086,1.026045,"POLYGON ((4936734.248 -1733533.078, 4936734.24..."
4,29124,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,120.052605,0.0,0.0,exact,NaN,2.085751,alta,0.705485,1.024828,"POLYGON ((4936734.248 -1833533.078, 4936734.24..."