In [16]:
import geopandas as gpd

In [17]:
gdf = gpd.read_file("data/Predicciones/mapa_continuo.gpkg")
gdf

,lat,lon,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,microplastics_log_est,microplastics_est,profile_eco,geometry
0,-78.0,-175.5,543.707048,-1.775068,34.395912,1.680748,27.419722,1.907441,311.153168,59.152695,0.211114,0.235053,cold_open_sea,POINT (-175.5 -78)
1,-78.0,-175.0,533.294654,-1.775068,34.395912,1.243596,27.419722,1.907441,311.153168,59.152695,0.210195,0.233919,cold_open_sea,POINT (-175 -78)
2,-78.0,-173.0,543.143622,-1.808737,34.373737,-0.760849,27.574869,1.912899,312.213226,57.888039,0.308657,0.361595,cold_open_sea,POINT (-173 -78)
3,-78.0,-172.5,540.559218,-1.808737,34.373737,-0.805667,27.574869,1.912899,312.213226,57.888039,0.308657,0.361595,cold_open_sea,POINT (-172.5 -78)
4,-78.0,-172.0,535.905487,-1.808737,34.373737,-0.708566,27.574869,1.912899,312.213226,57.888039,0.308657,0.361595,cold_open_sea,POINT (-172 -78)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127008,72.0,-15.0,425.634963,0.289420,34.764435,0.504466,11.316046,0.823883,318.571198,32.765865,0.315589,0.371066,cold_shelf,POINT (-15 72)
127009,72.0,25.5,94.266326,6.833642,34.894951,0.065487,6.138589,0.608244,298.023193,4.414944,0.395133,0.484582,cold_shelf,POINT (25.5 72)
127010,72.0,26.5,110.341777,6.723017,34.888157,0.365244,5.862425,0.607004,298.572815,4.962784,0.355206,0.426474,cold_shelf,POINT (26.5 72)
127011,72.0,27.0,111.642511,6.723017,34.888157,-0.597254,5.862425,0.607004,298.572815,4.962784,0.331746,0.393399,cold_shelf,POINT (27 72)
127012,72.0,27.5,98.314809,6.519808,34.888569,-0.687283,5.836751,0.615934,299.227234,5.952769,0.316624,0.372486,cold_shelf,POINT (27.5 72)

In [18]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 127013 entries, 0 to 127012
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   lat                    127013 non-null  float64
 1   lon                    127013 non-null  float64
 2   distance_to_coast_km   127013 non-null  float64
 3   temperature            127013 non-null  float32
 4   salinity               127013 non-null  float32
 5   chlorophyll            127013 non-null  float32
 6   nitrate                127013 non-null  float32
 7   phosphate              127013 non-null  float32
 8   oxygen_dissolved       127013 non-null  float32
 9   oxygen_utilization     127013 non-null  float32
 10  microplastics_log_est  127013 non-null  float64
 11  microplastics_est      127013 non-null  float64
 12  profile_eco            127011 non-null  object
 13  geometry               127013 non-null  geometry
dtypes: float32(7), float64(5), geometry(1), object(1)
memory usage: 10.2+ MB

In [19]:
gdf.describe()

,lat,lon,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,microplastics_log_est,microplastics_est
count,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000,127013.000000
mean,-10.007543,-9.046928,750.044877,7.997197,34.678719,0.532300,23.052828,1.671279,188.177490,110.283775,0.383477,28.486041
std,35.009586,111.011041,571.628432,4.463955,1.264769,6.216773,7.026030,0.502678,52.864658,48.267570,0.599799,673.731594
min,-78.000000,-179.500000,0.103413,-1.850811,5.000000,-1366.265503,0.000000,0.023326,37.909927,-5.241513,0.004230,0.004239
25%,-40.500000,-111.000000,278.209049,5.151471,34.468796,-0.269659,19.575056,1.410686,141.790955,81.606102,0.166744,0.181451
50%,-13.000000,-21.500000,620.359049,8.658937,34.672611,0.265012,24.424078,1.763284,197.913284,100.916283,0.267175,0.306270
75%,17.500000,90.500000,1110.119925,10.146996,34.979290,0.994706,28.254725,2.041040,230.406204,149.964447,0.436245,0.546888
max,72.000000,179.500000,2747.629560,30.365410,40.431507,853.870911,36.994316,5.037070,381.294861,250.507050,10.127362,25017.268590

In [20]:
gdf.iloc[[124887]]

,lat,lon,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,microplastics_log_est,microplastics_est,profile_eco,geometry
124887,59.5,-7.5,148.751067,9.397936,35.252747,-2.219914,10.615855,0.714665,269.808655,11.931182,4.395142,80.056151,cold_shelf,POINT (-7.5 59.5)

In [21]:
import numpy as np
y_pred = 0.106
y_real = float(np.expm1(y_pred))
y_real

0.11182187650653083

In [22]:
gdf2 = gpd.read_file("data/grid_ocean/grilla_agua_perfiles.gpkg")

In [23]:
gdf2.iloc[[124887]]

,lat,lon,distance_to_coast_km,temperature,salinity,chlorophyll,nitrate,phosphate,oxygen_dissolved,oxygen_utilization,cluster_num,profile_eco,geometry
124887,59.5,-6.5,112.662791,10.047992,35.207428,-1.54359,8.725164,0.624753,269.322052,7.819639,1,cold_shelf,POINT (-6.5 59.5)

In [24]:
y_pred2 = 0.106
y_real2 = float(np.expm1(y_pred))
y_real2

0.11182187650653083